source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'

source 'https://github.com/SwiftyJSON/SwiftyJSON.git'
platform :ios, '8.1'
pod 'SwiftyJSON'
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'